BUFF_SIZE = 1024
DEFAULT_ID = -1
LISTENING = 8
HEARTBEAT_TIME = 2
MAX_TRANSMISSION_DELAY = 5
MAX_PROCESSING_DELAY = 2
TOTAL_DELAY = (2 * MAX_TRANSMISSION_DELAY) + MAX_PROCESSING_DELAY

HEARTBEAT_TIME = 5